base:
  reports_dir: reports/train
  logging_level: INFO

data:
  raw_data: data/train.txt
  train_data: data/train.csv
  val_data: data/val.csv
  reference_data: data/reference_data.csv
  
  target_col: INCOME
  prediction_col: PREDICT
  numerical_features: ['AGE', 'EDUCATIONAL-NUM', 'CAPITAL-GAIN', 'CAPITAL-LOSS', 'HOURS-PER-WEEK']
  categorical_features: ['WORKCLASS', 'EDUCATION', 'MARITAL-STATUS', 'OCCUPATION', 'RELATIONSHIP', 'GENDER']
  test_size_ratio: 0.2

train:
  depth: 4
  iterations: 200
  learning_rate: 0.1
  model_path: models/model.joblib

extract_data:

evaluate:
  model_performance_path: model_performance.html
  metrics_path: metrics.json

  
