base:
  logging_level: INFO

data:
  raw_data: 
    /Users/kiennguyen/interview/tpbank2/data/serve_26bbf4fb-580a-468d-a816-800cdf990b00.csv
  test_data: 
    /Users/kiennguyen/interview/tpbank2/data/serve_26bbf4fb-580a-468d-a816-800cdf990b00_processed.csv
  target_col: INCOME
  prediction_col: PREDICT
  batch_id: 26bbf4fb-580a-468d-a816-800cdf990b00

predict:
  model_path: /Users/kiennguyen/interview/tpbank2/models/model.joblib
  predictions_dir: /Users/kiennguyen/interview/tpbank2/data/predictions

