base:
  logging_level: INFO

data:
  raw_data: data/test.txt
  test_data: data/test.csv
  target_col: INCOME
  prediction_col: prediction
  
predict: 
  model_path: models/model.joblib
  predictions_dir: data/predictions
  
